name: Pull Request Workflow

on: 
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  pull-request-job:
    name: Status Checks
    runs-on: ubuntu-latest
    steps:
      - name: Viperlight
        run: |
          wget -q https://viperlight-scanner.s3.amazonaws.com/latest/.viperlightrc
          wget -q https://viperlight-scanner.s3.amazonaws.com/latest/codescan-funcs.sh
          wget -q https://viperlight-scanner.s3.amazonaws.com/latest/codescan-postbuild-default.sh
          wget -q https://viperlight-scanner.s3.amazonaws.com/latest/viperlight.zip
          unzip -q viperlight.zip -d ../viperlight
          rm -r ./viperlight.zip
          default_scan="./codescan-postbuild-default.sh"
          if [ -f "$default_scan" ]; then
            chmod +x $default_scan
          else
            default_scan = "viperlight scan"
          fi
          custom_scancmd=./codescan-postbuild-custom.sh
          if [ -f "$custom_scancmd" ]; then
            chmod +x $custom_scancmd
            $custom_scancmd
          else
            $default_scan
          fi
